ICE:
  occurrence: 0.6
  science_value: 0.1
  density: 997 # kg/m^3
  # color: {r: 125, g: 217, b: 255}
  color: {r: 0, g: 255, b: 0}

SALT_ICE:
  occurrence: 0.3
  science_value: 0.6
  density: 0 # TODO
  # color: {r: 204, g: 204, b: 255}
  color: {r: 0, g: 0, b: 255}

SALT:
  occurrence: 0.1
  science_value: 0.1
  density: 0 # TODO
  # color: {r: 231, g: 231, b: 245}
  color: {r: 255, g: 0, b: 0}
